//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurssovay_1.Bases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KadrovoeEntities : DbContext
    {
        public KadrovoeEntities()
            : base("name=KadrovoeEntities")
        {
        }

        private static KadrovoeEntities _context;

        

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public static KadrovoeEntities GetContext()
        {
            if (_context == null)
                _context = new KadrovoeEntities();
            return _context;
        }

        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Statements> Statements { get; set; }
        public virtual DbSet<Statements1> Statements1 { get; set; }
        public virtual DbSet<Status_> Status_ { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
    }
}
